changing routes for IceRaids and adding Check Point Files for back end and front end.
smcueto/salientAlert pull request #3
Opened 2018-06-08 19:47 UTC by smcueto

Axios call for Check Point is throwing error msg.

2018-06-08 21:30 UTC, fluxsauce requested changes
Good start! Here's a first pass...

2018-06-08 21:30 UTC, fluxsauce commented on server/models/CheckPointmodel.js
> +var CheckPointCollectionModel = new Schema({
`CheckPointModel`

2018-06-08 21:30 UTC, fluxsauce commented on server/models/CheckPointmodel.js
> +var mongoose = require('mongoose');
Use `const` if it never changes.

2018-06-08 21:30 UTC, fluxsauce commented on server/models/IceRaidModel.js
> +var mongoose = require('mongoose');
Use `const` if it never changes.

2018-06-08 21:30 UTC, fluxsauce commented on server/models/IceRaidModel.js
> +var iceRaidCollectionModel = new Schema({
`IceRaidModel`

2018-06-08 21:30 UTC, fluxsauce commented on server/models/CheckPointmodel.js
> +  checkPointDate: {
You've got two fields for the date, date and time, and neither of them use the native `Date` storage. I'd recommend using just one field and https://docs.mongodb.com/manual/reference/bson-types/#date

2018-06-08 21:30 UTC, fluxsauce commented on server/models/IceRaidModel.js
> +  iceRaidDate: {
You've got two fields for the date, date and time, and neither of them use the native `Date` storage. I'd recommend using just one field and https://docs.mongodb.com/manual/reference/bson-types/#date

2018-06-08 21:30 UTC, fluxsauce commented on server/routes/CheckServerRoutes.js
> +      console.log(err);
Return an error rather than log

2018-06-08 21:30 UTC, fluxsauce commented on server/routes/CheckServerRoutes.js
> +        res.json('Server added successfully');
Server?

2018-06-08 21:30 UTC, fluxsauce commented on server/routes/CheckServerRoutes.js
> +    res.status(400).send("unable to save to database");
Should this be a 500?

2018-06-08 21:30 UTC, fluxsauce commented on server/routes/IceServerRoutes.js
> +const iceCollectionDirectory = require('../models/IceRaidModel');
Best practice is to be consistent with the naming, there's no value in calling it something different and if anything it's more confusing. `IceRaidModel` is fine.

2018-06-08 21:30 UTC, fluxsauce commented on server/routes/IceServerRoutes.js
> +            res.status(400).send("unable to update the database");
500?

2018-06-08 23:59 UTC, merged

2018-06-09 00:00 UTC, smcueto commented
@fluxsauce applied 👍